package com.example.meshmessenger.mesh

import android.util.Base64
import java.nio.charset.StandardCharsets

/**
 * Versioned contact card shared through QR, clipboard and Android share.
 *
 * Current format:
 * MM1|nodeId|base64url(name)|publicKeyBase64
 *
 * The node ID is never trusted: it is recomputed from the public key and
 * must match the supplied ID before a card can be imported.
 */
object ContactCard {
    private const val PREFIX = "MM1"
    private const val SEPARATOR = "|"

    data class Parsed(
        val nodeId: String,
        val displayName: String,
        val publicKeyBase64: String,
        val isLegacy: Boolean
    )

    fun create(nodeId: String, displayName: String, publicKeyBase64: String): String {
        val publicKey = runCatching { CryptoManager.publicKeyFromBase64(publicKeyBase64) }
            .getOrElse { throw IllegalArgumentException("Некорректный публичный ключ") }

        val derivedNodeId = CryptoManager.keyId(publicKey)
        require(nodeId == derivedNodeId) { "Node ID не соответствует публичному ключу" }

        val encodedName = Base64.encodeToString(
            displayName.trim().ifBlank { "Контакт" }.toByteArray(StandardCharsets.UTF_8),
            Base64.URL_SAFE or Base64.NO_WRAP or Base64.NO_PADDING
        )

        return listOf(PREFIX, derivedNodeId, encodedName, publicKeyBase64).joinToString(SEPARATOR)
    }

    fun parse(raw: String): Parsed {
        val value = raw.trim()
        require(value.isNotEmpty()) { "Пустая контактная карточка" }

        val parts = value.split(SEPARATOR)
        val parsed = when {
            parts.size == 4 && parts[0] == PREFIX -> {
                val nodeId = parts[1].trim()
                val name = decodeName(parts[2])
                val publicKey = parts[3].trim()
                Parsed(nodeId, name, publicKey, false)
            }
            parts.size == 3 -> {
                // Compatibility with cards generated by older MeshMessenger builds.
                Parsed(
                    nodeId = parts[0].trim(),
                    displayName = parts[1].trim().ifBlank { "Контакт" },
                    publicKeyBase64 = parts[2].trim(),
                    isLegacy = true
                )
            }
            else -> throw IllegalArgumentException("Неверный формат контактной карточки")
        }

        require(parsed.nodeId.matches(Regex("[0-9a-fA-F]{16}"))) {
            "Неверный Node ID"
        }

        val publicKey = runCatching {
            CryptoManager.publicKeyFromBase64(parsed.publicKeyBase64)
        }.getOrElse {
            throw IllegalArgumentException("Неверный публичный ключ")
        }

        val derivedNodeId = CryptoManager.keyId(publicKey)
        require(parsed.nodeId.equals(derivedNodeId, ignoreCase = true)) {
            "Node ID не соответствует публичному ключу"
        }

        return parsed.copy(
            nodeId = derivedNodeId,
            publicKeyBase64 = CryptoManager.publicKeyBase64(publicKey),
            displayName = parsed.displayName.trim().ifBlank { "Контакт" }.take(64)
        )
    }

    private fun decodeName(encoded: String): String {
        return runCatching {
            String(Base64.decode(encoded, Base64.URL_SAFE or Base64.NO_WRAP), StandardCharsets.UTF_8)
        }.getOrElse {
            throw IllegalArgumentException("Неверное имя в контактной карточке")
        }
    }
}
